apiVersion: v1
kind: Service
metadata:
  name: httpd-service-syaiba
  namespace: httpd-namespace-syaiba
spec:
  type: NodePort
  selector:
    app: httpd_app_syaiba
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004